name: Go Build and Test

on: 
  push:
    branches:
      - main
      - v1.30.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17 # Update this to the desired Go version

    - name: Build
      run: |
          
          go build main.go
          ls -ltra
           pwd

    - name: Upload kubeconfig as artifact
      uses: actions/upload-artifact@v2
      with:
        name: spincli
        path: /home/runner/work/spin/spin/main
        retention-days: 1

 
   # - name: Run tmate
    #  uses: mxschmitt/action-tmate@v2



    # Add additional steps as needed for your workflow, such as deploying or publishing artifacts.
