name: Go Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17 # Update this to the desired Go version

    - name: Build
      run: go build 



    # Add additional steps as needed for your workflow, such as deploying or publishing artifacts.
